package Analyse;

public class AnalyseLexicale {

    private static Integer TRANSITIONS[][] = {
            // espace       m      h     t      p      s     f   chard  intval     (      )      ,
            {        0 ,    1 ,    6 ,  13 ,   23 ,   28 ,  33 ,     0 ,     0,    0 ,    0 ,    0 },
            {     null , null , null, null , null , null, null ,  null ,  null,    2 , null , null },
            {     null , null , null, null , null , null, null ,  null ,     3,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,    4 },
            {     null , null , null, null , null , null, null ,  null ,     5,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  101 , null },
            {     null , null , null, null , null , null, null ,  null ,  null,     7, null , null },
            {     null , null , null, null , null , null, null ,  null ,     8,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,    9 },
            {     null , null , null, null , null , null, null ,  null ,    10,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   11},
            {     null , null , null, null , null , null, null ,  null ,    12,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  102 , null },
            {     null , null , null, null , null , null, null ,  null ,  null,    14, null , null },
            {     null , null , null, null , null , null, null ,  null ,    15,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   16 },
            {     null , null , null, null , null , null, null ,  null ,    17,  null, null , null },
            {     null , null , null, null , null , null, null ,    18 ,  null,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   19 },
            {     null , null , null, null , null , null, null ,  null ,    20,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   21 },
            {     null , null , null, null , null , null, null ,  null ,    22,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  103 , null },
            {     null , null , null, null , null , null, null ,  null ,  null,    24, null , null },
            {     null , null , null, null , null , null, null ,  null ,    25,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   26 },
            {     null , null , null, null , null , null, null ,  null ,    27,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  104 , null },
            {     null , null , null, null , null , null, null ,  null ,  null,    29, null , null },
            {     null , null , null, null , null , null, null ,  null ,    30,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   31 },
            {     null , null , null, null , null , null, null ,  null ,    32,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  105 , null },
            {     null , null , null, null , null , null, null ,  null ,  null,    34, null , null },
            {     null , null , null, null , null , null, null ,  null ,    35,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   36 },
            {     null , null , null, null , null , null, null ,  null ,    37,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   38 },
            {     null , null , null, null , null , null, null ,    39 ,  null,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  106 , null },
            {     null , null , null, null , null , null, null ,  null ,  null,    41, null , null },
            {     null , null , null, null , null , null, null ,  null ,    42,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   43 },
            {     null , null , null, null , null , null, null ,  null ,    44,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   45 },
            {     null , null , null, null , null , null, null ,  null ,    46,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null, null ,   47 },
            {     null , null , null, null , null , null, null ,  null ,    48,  null, null , null },
            {     null , null , null, null , null , null, null ,  null ,  null,  null,  107 , null },


    };
}